import { newArray } from '@angular/compiler/src/util';
import { Component, OnInit } from '@angular/core';
import { Resume } from '../Resume';

@Component({
  selector: 'app-resume',
  templateUrl: './resume.component.html',
  styleUrls: ['./resume.component.css'],
})
export class ResumeComponent implements OnInit {
  resume: Resume;
  constructor() {}

  //Generated by typescript 1.8.10
  // var names = new Array("Mary", "Tom", "Jack", "Jill");
  // for (var i = 0; i < names.length; i++) {
  //   console.log(names[i]);
  // }

  // Сгенерировано посредством typescript 1.8.10
  // var names = new Array("Mary", "Tom", "Jack", "Jill");
  // for (var i = 0; i < names.length; i++) {
  //    console.log(names[i]);
  // }

  ngOnInit(): void {
    this.resume = new Resume();
    this.resume.title = 'Nakonechnyi Serhii';
    this.resume.description = 'BackEnd/FrontEnd Web Developer';
    var expirience = new Array('C#', 'ASPNET MVC', 'ASPNET Core');
    for (var i = 0; i < expirience.length; i++) {
      this.resume.expirience = expirience;
    }

    //this.resume.expirience = new Array("- C#", "- ASPNET MVC");
    // this.resume.expirience = `
    // - C# \n
    // - ASPNET MVC \n
    // - ASPNET Core \n
    // - React \n
    // - Angular \n
    // - NodeJS`;
    this.resume.skills = `
    - Create C# Console and Web Application \n 
    - Create Web Application`;
  }
}
